### PR TITLE
Replace old logo with new one

### PR DESCRIPTION
**Pull request by planger**
Contributed on behalf of STMicroelectronics

### CODE REVIEW

**Comment by jonahgraham** [comment]
@planger change looks ok to me. Can I leave it with you to submit helpdesk ticket to get other places updated as requested by @netomi  in https://github.com/eclipse-cdt-cloud/.eclipsefdn/issues/3#issuecomment-1611424192?

**Comment by planger** [comment]
@jonahgraham Sure, I'll open the helpdesk ticket soon (probably tomorrow). Thanks for the ping!

**Comment by planger** [comment]
Fyi, I've opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3334 and changed the logo at https://projects.eclipse.org/projects/ecd.cdt-cloud

**Review by sdirix — APPROVED** [review]
LGTM!

**Pull request merged**
