### PR TITLE
Add links to try now page for CDT Cloud and improve wording

### PR DESCRIPTION
**Pull request by planger**
Contributed on behalf of STMicroelectronics.

### CODE REVIEW

**Review by sdirix — APPROVED** [review]
The changes themselves are fine. We should just clarify the point of time to merge this change as the Theia cloud variant of CDT Cloud Blueprint is not in a good state.

**Comment by planger** [comment]
@sdirix Is the try-now version now ready get advertised on the website? I've updated this branch as it had conflicts. Now it should be fine to go, if you agree.

**Comment by planger** [comment]
@sdirix Can we already publish the Try Now link on the webpage? I believe the try now is now in a quite good shape, isn't it?

**Comment by planger** [comment]
I've updated this branch and also improved the wording around CDT Cloud Blueprint. Should be merged once 1.0 is available. Thank you!

**Pull request merged**
